### ISSUE TITLE
Feed crashes application while scrolling

### ISSUE THREAD

**Issue by emrebil** [bounswe/bounswe2018group1#117]
I tried this on both my computer and phone. If you scroll down continuously on feed fragment, the application will crash and stop itself. Logs from Android Studio in the following from beginning of scroll to application stop:

I/System.out: Response: {"content":[{"userId":3,"userNickname":"ailerle","userFirstName":"Akin","userLastName":"Ilerle","headline":"string","dateOfCreation":"2018-11-27T10:32:46.571+0000","listOfLocations":[{"locationName":"string","longitude":0,"latitude":0}],"startDateHH":0,"startDateDD":0,"startDateMM":10,"startDateYYYY":2017,"endDateHH":0,"endDateDD":0,"endDateMM":11,"endDateYYYY":2017,"listOfTags":[{"text":"string"}],"listOfItems":[{"id":5,"body":"string"}],"updatedTime":"2018-11-27"},{"userId":3,"userNickname":"ailerle","userFirstName":"Akin","userLastName":"Ilerle","headline":"string","dateOfCreation":"2018-11-27T10:32:51.297+0000","listOfLocations":[{"locationName":"string","longitude":0,"latitude":0}],"startDateHH":0,"startDateDD":0,"startDateMM":10,"startDateYYYY":2017,"endDateHH":0,"endDateDD":0,"endDateMM":11,"endDateYYYY":2017,"listOfTags":[{"text":"string"}],"listOfItems":[{"id":9,"body":"string"}],"updatedTime":"2018-11-27"},{"userId":3,"userNickname":"ailerle","userFirstName":"Akin","userLastName":"Ilerle","headline":"string","dateOfCreation":"2018-11-27T10:32:51.627+0000","listOfLocations":[{"locationName":"string","longitude":0,"latitude":0}],"startDateHH":0,"startDateDD":0,"startDateMM":10,"startDateYYYY":2017,"endDateHH":0,"endDateDD":0,"endDateMM":11,"endDateYYYY":2017,"listOfTags":[{"text":"string"}],"listOfItems":[{"id":13,"body":"string"}],"updatedTime":"2018-11-27"},{"userId":3,"userNickname":"ailerle","userFirstName":"Akin","userLastName":"Ilerle","headline":"string","dateOfCreation":"2018-11-27T10:32:51.979+0000","listOfLocations":[{"locationName":"string","longitude":0,"latitude":0}],"startDateHH":0,"startDateDD":0,"startDateMM":10,"startDateYYYY":2017,"endDateHH":0,"endDateDD":0,"endDateMM":11,"endDateYYYY":2017,"listOfTags":[{"text":"string"}],"listOfItems":[{"id":17,"body":"string"}],"updatedTime":"2018-11-27"}],"pageable":{"sort":{"sorted":false,"unsorted":true},"pageSize":4,"pageNumber":0,"offset":0,"paged":true,"unpaged":false},"totalPages":1,"totalElements":4,"last":true,"first":true,"sort":{"sorted":false,"unsorted":true},"numberOfElements":4,"size":4,"number":0}
I/System.out: Response: {"content":[{"userId":3,"userNickname":"ailerle","userFirstName":"Akin","userLastName":"Ilerle","headline":"string","dateOfCreation":"2018-11-27T10:32:52.325+0000","listOfLocations":[{"locationName":"string","longitude":0,"latitude":0}],"startDateHH":0,"startDateDD":0,"startDateMM":10,"startDateYYYY":2017,"endDateHH":0,"endDateDD":0,"endDateMM":11,"endDateYYYY":2017,"listOfTags":[{"text":"string"}],"listOfItems":[{"id":21,"body":"string"}],"updatedTime":"2018-11-27"},{"userId":3,"userNickname":"ailerle","userFirstName":"Akin","userLastName":"Ilerle","headline":"string","dateOfCreation":"2018-11-27T10:32:52.675+0000","listOfLocations":[{"locationName":"string","longitude":0,"latitude":0}],"startDateHH":0,"startDateDD":0,"startDateMM":10,"startDateYYYY":2017,"endDateHH":0,"endDateDD":0,"endDateMM":11,"endDateYYYY":2017,"listOfTags":[{"text":"string"}],"listOfItems":[{"id":25,"body":"string"}],"updatedTime":"2018-11-27"},{"userId":3,"userNickname":"ailerle","userFirstName":"Akin","userLastName":"Ilerle","headline":"string","dateOfCreation":"2018-11-27T10:32:52.997+0000","listOfLocations":[{"locationName":"string","longitude":0,"latitude":0}],"startDateHH":0,"startDateDD":0,"startDateMM":10,"startDateYYYY":2017,"endDateHH":0,"endDateDD":0,"endDateMM":11,"endDateYYYY":2017,"listOfTags":[{"text":"string"}],"listOfItems":[{"id":29,"body":"string"}],"updatedTime":"2018-11-27"},{"userId":3,"userNickname":"ailerle","userFirstName":"Akin","userLastName":"Ilerle","headline":"string","dateOfCreation":"2018-11-27T10:32:53.363+0000","listOfLocations":[{"locationName":"string","longitude":0,"latitude":0}],"startDateHH":0,"startDateDD":0,"startDateMM":10,"startDateYYYY":2017,"endDateHH":0,"endDateDD":0,"endDateMM":11,"endDateYYYY":2017,"listOfTags":[{"text":"string"}],"listOfItems":[{"id":33,"body":"string"}],"updatedTime":"2018-11-27"}],"pageable":{"sort":{"sorted":false,"unsorted":true},"pageSize":4,"pageNumber":1,"offset":4,"paged":true,"unpaged":false},"totalPages":2,"totalElements":8,"last":true,"first":false,"sort":{"sorted":false,"unsorted":true},"numberOfElements":4,"size":4,"number":1}
I/System.out: Response: {"content":[{"userId":3,"userNickname":"ailerle","userFirstName":"Akin","userLastName":"Ilerle","headline":"string","dateOfCreation":"2018-11-27T10:32:53.683+0000","listOfLocations":[{"locationName":"string","longitude":0,"latitude":0}],"startDateHH":0,"startDateDD":0,"startDateMM":10,"startDateYYYY":2017,"endDateHH":0,"endDateDD":0,"endDateMM":11,"endDateYYYY":2017,"listOfTags":[{"text":"string"}],"listOfItems":[{"id":37,"body":"string"}],"updatedTime":"2018-11-27"},{"userId":3,"userNickname":"ailerle","userFirstName":"Akin","userLastName":"Ilerle","headline":"string","dateOfCreation":"2018-11-27T10:32:54.033+0000","listOfLocations":[{"locationName":"string","longitude":0,"latitude":0}],"startDateHH":0,"startDateDD":0,"startDateMM":10,"startDateYYYY":2017,"endDateHH":0,"endDateDD":0,"endDateMM":11,"endDateYYYY":2017,"listOfTags":[{"text":"string"}],"listOfItems":[{"id":41,"body":"string"}],"updatedTime":"2018-11-27"},{"userId":44,"userNickname":"a","userFirstName":"a","userLastName":"a","headline":"String dışında bişey","dateOfCreation":"2018-11-27T17:24:29.959+0000","listOfLocations":[{"locationName":"Boğaziçi University","longitude":0,"latitude":0},{"locationName":"CmpE","longitude":0,"latitude":0}],"startDateHH":0,"startDateDD":17,"startDateMM":9,"startDateYYYY":2018,"endDateHH":0,"endDateDD":27,"endDateMM":11,"endDateYYYY":2018,"listOfTags":[{"text":"tag1"},{"text":"tag2"},{"text":"tag3"},{"text":"tag4"}],"listOfItems":[{"id":49,"body":"asdasdasd"},{"id":50,"body":"qweqweqwe"},{"id":51,"body":"zxczxczxc"}],"updatedTime":"2018-11-27"},{"userId":2,"userNickname":"aa","userFirstName":"Name","userLastName":"Surname","headline":"string","dateOfCreation":"2018-11-30T20:02:12.786+0000","listOfLocations":[{"locationName":"string","longitude":0,"latitude":0}],"startDateHH":0,"startDateDD":0,"startDateMM":0,"startDateYYYY":0,"endDateHH":0,"endDateDD":0,"endDateMM":0,"endDateYYYY":0,"listOfTags":[{"text":"string"}],"listOfItems":[{"id":58,"body":"string"}],"updatedTime":"2018-11-30"}],"pageable":{"sort":{"sorted":false,"unsorted":true},"pageSize":4,"pageNumber":2,"offset":8,"paged":true,"unpaged":false},"totalPages":3,"totalElements":12,"last":true,"first":false,"sort":{"sorted":false,"unsorted":true},"numberOfElements":4,"size":4,"number":2}
I/System.out: Response: {"content":[{"userId":2,"userNickname":"aa","userFirstName":"Name","userLastName":"Surname","headline":"bu","dateOfCreation":"2018-11-30T20:26:16.172+0000","listOfLocations":[{"locationName":"string","longitude":0,"latitude":0}],"startDateHH":0,"startDateDD":0,"startDateMM":0,"startDateYYYY":0,"endDateHH":0,"endDateDD":0,"endDateMM":0,"endDateYYYY":0,"listOfTags":[{"text":"string"}],"listOfItems":[{"id":66,"body":"string"}],"updatedTime":"2018-11-30"},{"userId":2,"userNickname":"aa","userFirstName":"Name","userLastName":"Surname","headline":"string","dateOfCreation":"2018-11-30T21:33:00.740+0000","listOfLocations":[{"locationName":"string","longitude":0,"latitude":0}],"startDateHH":0,"startDateDD":0,"startDateMM":0,"startDateYYYY":0,"endDateHH":0,"endDateDD":0,"endDateMM":0,"endDateYYYY":0,"listOfTags":[{"text":"string"}],"listOfItems":[{"id":70,"body":"string"}],"updatedTime":"2018-11-30"},{"userId":2,"userNickname":"aa","userFirstName":"Name","userLastName":"Surname","headline":"string","dateOfCreation":"2018-11-30T21:33:35.172+0000","listOfLocations":[{"locationName":"string","longitude":0,"latitude":0}],"startDateHH":0,"startDateDD":0,"startDateMM":0,"startDateYYYY":0,"endDateHH":16,"endDateDD":0,"endDateMM":0,"endDateYYYY":0,"listOfTags":[{"text":"string"}],"listOfItems":[{"id":74,"body":"string"}],"updatedTime":"2018-11-30"},{"userId":2,"userNickname":"aa","userFirstName":"Name","userLastName":"Surname","headline":"string","dateOfCreation":"2018-11-30T21:34:22.384+0000","listOfLocations":[{"locationName":"string","longitude":0,"latitude":0}],"startDateHH":0,"startDateDD":0,"startDateMM":0,"startDateYYYY":0,"endDateHH":16,"endDateDD":-1,"endDateMM":0,"endDateYYYY":0,"listOfTags":[{"text":"string"}],"listOfItems":[{"id":78,"body":"string"}],"updatedTime":"2018-11-30"}],"pageable":{"sort":{"sorted":false,"unsorted":true},"pageSize":4,"pageNumber":3,"offset":12,"paged":true,"unpaged":false},"totalPages":4,"totalElements":16,"last":true,"first":false,"sort":{"sorted":false,"unsorted":true},"numberOfElements":4,"size":4,"number":3}
I/System.out: Response: {"content":[{"userId":2,"userNickname":"aa","userFirstName":"Name","userLastName":"Surname","headline":"string","dateOfCreation":"2018-11-30T22:08:24.756+0000","listOfLocations":[{"locationName":"string","longitude":0,"latitude":0}],"startDateHH":0,"startDateDD":0,"startDateMM":0,"startDateYYYY":0,"endDateHH":0,"endDateDD":0,"endDateMM":0,"endDateYYYY":0,"listOfTags":[{"text":"string"}],"listOfItems":[{"id":82,"body":"string"}],"updatedTime":"2018-11-30"},{"userId":2,"userNickname":"aa","userFirstName":"Name","userLastName":"Surname","headline":"string","dateOfCreation":"2018-11-30T23:41:55.238+0000","listOfLocations":[{"locationName":"string","longitude":0,"latitude":0}],"startDateHH":0,"startDateDD":0,"startDateMM":0,"startDateYYYY":0,"endDateHH":0,"endDateDD":0,"endDateMM":5,"endDateYYYY":7,"listOfTags":[{"text":"string"}],"listOfItems":[{"id":86,"body":"string"}],"updatedTime":"2018-11-30"},{"userId":2,"userNickname":"aa","userFirstName":"Name","userLastName":"Surname","headline":"Qweqweqweqwe","dateOfCreation":"2018-11-30T23:54:30.692+0000","listOfLocations":[],"startDateHH":0,"startDateDD":0,"startDateMM":3123,"startDateYYYY":312312,"endDateHH":0,"endDateDD":0,"endDateMM":3123,"endDateYYYY":123122,"listOfTags":[{"text":"Tag"}],"listOfItems":[],"updatedTime":"2018-11-30"},{"userId":2,"userNickname":"aa","userFirstName":"Name","userLastName":"Surname","headline":"","dateOfCreation":"2018-12-01T00:02:07.089+0000","listOfLocations":[],"startDateHH":0,"startDateDD":0,"startDateMM":0,"startDateYYYY":0,"endDateHH":0,"endDateDD":0,"endDateMM":0,"endDateYYYY":0,"listOfTags":[{"text":"Tag"}],"listOfItems":[],"updatedTime":"2018-12-01"}],"pageable":{"sort":{"sorted":false,"unsorted":true},"pageSize":4,"pageNumber":4,"offset":16,"paged":true,"unpaged":false},"totalPages":5,"totalElements":20,"last":true,"first":false,"sort":{"sorted":false,"unsorted":true},"numberOfElements":4,"size":4,"number":4}
E/InputEventReceiver: Exception dispatching input event.
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: bounswe2018group1.cmpe451, PID: 20798
    java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at com.google.gson.JsonArray.get(JsonArray.java:194)
        at bounswe2018group1.cmpe451.helpers.MemoryAdapter.getView(MemoryAdapter.java:71)
        at android.widget.AbsListView.obtainView(AbsListView.java:2344)
        at android.widget.ListView.makeAndAddView(ListView.java:1864)
        at android.widget.ListView.fillDown(ListView.java:698)
        at android.widget.ListView.fillGap(ListView.java:662)
        at android.widget.AbsListView.trackMotionScroll(AbsListView.java:4968)
        at android.widget.AbsListView.scrollIfNeeded(AbsListView.java:3398)
        at android.widget.AbsListView.onTouchMove(AbsListView.java:3774)
        at android.widget.AbsListView.onTouchEvent(AbsListView.java:3612)
        at android.view.View.dispatchTouchEvent(View.java:8388)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2424)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2158)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2314)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1692)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2739)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2275)
        at android.view.View.dispatchPointerEvent(View.java:8578)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4021)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3887)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3578)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3476)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3635)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3476)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5701)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5675)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5646)
    	at android.view.ViewRootImpl$WindowInput

**Comment by denizetkar** [comment]
The bug was caused because in some memories there were no locations assigned to them and in the memory feed for each memory the location of occurrence was assumed to be the first location so when the code tried to access the first location from the "listOfLocations" it caused a "java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0" bug.

It should be fixed now with the commit: 7e41c78b78a9cac59702c7e422ab112fc4709fce
